### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by BigDeepBlue** [dcomrad/graduate_work#35]
Отличная работа. Очень качественная.

Хотелось бы отметить:
- простой и удобный запуск проекта
- здорово, что у вас есть тесты, настроено логирование
- проект имеет понятную структуру, очень понравилось как вы разбили код на модули
- понравились ваши вьюхи в основном сервисе

## Oбщие комментарии
- Возможно функции `get_users_api_url`, `get_cancel_sub_api_url()`, `get_refund_api_url()` имеет смысл сделать строковыми константами.
- requests поддерживает вызовы и в [таком виде](https://github.com/psf/requests/blob/839a8edec37c81a18ac8332cfbd44f44e1ae6206/src/requests/api.py#L115): `request("get", "https://ya.ru")`. В [этом месте](https://github.com/dcomrad/graduate_work/blob/625f5e70bed71f08d19a397bd3b1f63bdbcca226/billing-service/admin-panel/utils/api.py#L79) лучше избавиться от `getattr`.
## Dockefile
- Обновление системных пакетов и установку зависимостей Python лучше поменять местами, потому что зависимости Python чаще меняются в проекте, поэтому их выгоднее держать в слое выше; некоторые python зависимости могут требовать системных библиотек.
- файлы docker-compose не обязательно прописывать полностью. Можно использовать [merge](https://docs.docker.com/compose/multiple-compose-files/merge/) 
## Admin Panel
- Правильно ли я понимаю, что из админки вы запросы отправляете напрямую в другие сервисы? В целом это норм, для надёжности лучше вставить очередь между ними.

## Worker
- Возможно вместо [запросов на каждую подписку](https://github.com/dcomrad/graduate_work/blob/625f5e70bed71f08d19a397bd3b1f63bdbcca226/billing-service/worker/src/main.py#L17-L26) имеет смысл отправлять список айдишников пачками.
- Нет ли необходимости в [том же участке кода](https://github.com/dcomrad/graduate_work/blob/625f5e70bed71f08d19a397bd3b1f63bdbcca226/billing-service/worker/src/main.py#L17-L26) обрабатывать исключения?

**Comment by dcomrad** [comment]
`Возможно функции get_users_api_url, get_cancel_sub_api_url(), get_refund_api_url() имеет смысл сделать строковыми константами.`

Поправили

**Comment by dcomrad** [comment]
`requests поддерживает вызовы и в [таком виде](https://github.com/psf/requests/blob/839a8edec37c81a18ac8332cfbd44f44e1ae6206/src/requests/api.py#L115): request("get", "https://ya.ru"). В [этом месте](https://github.com/dcomrad/graduate_work/blob/625f5e70bed71f08d19a397bd3b1f63bdbcca226/billing-service/admin-panel/utils/api.py#L79) лучше избавиться от getattr`

Поправили

**Comment by dcomrad** [comment]
> Обновление системных пакетов и установку зависимостей Python лучше поменять местами, потому что зависимости Python чаще меняются в проекте, поэтому их выгоднее держать в слое выше; некоторые python зависимости могут требовать системных библиотек.

Выделаили обновление обновление системынх пакетов в отдельную команду и раположили раньше, чтобы при обновлении зависимостей, слой с системынми библиотеками не затрагивался.

**Comment by dcomrad** [comment]
> файлы docker-compose не обязательно прописывать полностью. Можно использовать [merge](https://docs.docker.com/compose/multiple-compose-files/merge/)

Классный подход. Применили его.

**Comment by dcomrad** [comment]
> Правильно ли я понимаю, что из админки вы запросы отправляете напрямую в другие сервисы? В целом это норм, для надёжности лучше вставить очередь между ними.

Да, всё так. По замыслу, функция админа больше мониторинговая. Внедрёно два доступных действия:
* "отмена" подписки пользователя (отключение автопродления) - текущая подписка пользователя сохраняется, но по её истечению нового списания не произоёдет
* возврат средств - отмена последней транзакции с деактивацией текущей подписки

Оба действия могут запрошены пользователем письменно по email в случае случайной активации подписки (например, сделали дети на телефоне родителей). Мы к тому, что действия эти будут разовыми и являться скорее исключением, чем правилом. Поэтому, мы решили не усложнять схему взаимодействия для этого функционала и сделать прямое управление.

**Comment by dcomrad** [comment]
> Возможно вместо [запросов на каждую подписку](https://github.com/dcomrad/graduate_work/blob/625f5e70bed71f08d19a397bd3b1f63bdbcca226/billing-service/worker/src/main.py#L17-L26) имеет смысл отправлять список айдишников пачками.

Изменили сигнатуру эндпоинта. Теперь он принимает список пользователей и их подписок, а запрос из воркера отправляется пачкой.

**Comment by dcomrad** [comment]
> Нет ли необходимости в [том же участке кода](https://github.com/dcomrad/graduate_work/blob/625f5e70bed71f08d19a397bd3b1f63bdbcca226/billing-service/worker/src/main.py#L17-L26) обрабатывать исключения?

Добавили обработку исключения на доступ к БД. Отсутствие доступа к сервису обрабатывается в перехвате исключения aiohttp.ClientError в функции make_http_request.

**Comment by BigDeepBlue** [comment]
LGTM.
